#!/usr/bin/env sh

./gradlew :common:clean :common:build :common:install
./gradlew :kodein-di-android-components:clean :kodein-di-android-components:build :kodein-di-android-components:install
./gradlew :kodein-di-androidx-components:clean :kodein-di-androidx-components:build :kodein-di-androidx-components:install
./gradlew :kodein-di-android-material-components:clean :kodein-di-android-material-components:build :kodein-di-android-material-components:install
