#!/usr/bin/env sh

./gradlew :common:clean :common:build :common:publish --no-daemon --no-parallel && \
./gradlew :kodein-di-android-components:clean :kodein-di-android-components:build :kodein-di-android-components:publish --no-daemon --no-parallel && \
./gradlew :kodein-di-androidx-components:clean :kodein-di-androidx-components:build :kodein-di-androidx-components:publish --no-daemon --no-parallel && \
./gradlew :kodein-di-android-material-components:clean :kodein-di-android-material-components:build :kodein-di-android-material-components:publish --no-daemon --no-parallel && \

if ! grep -q -- "VERSION_NAME=.*-SNAPSHOT" gradle.properties;
then
./gradlew closeAndReleaseRepository
else
echo "Nothing else to do for a snapshot"
fi
